### ISSUE TITLE
[Future request] Disable ligatures on selected text

### ISSUE THREAD

**Issue by kanlukasz** [CoenraadS/vscode-Disable-Ligatures#4]
Hello,
I have one idea.

Option to disable ligatures only on selected text could be useful.

Something like:
```"disableLigatures.mode": "selection"```

**Comment by kanlukasz** [comment]
Unfortunately, I have to close this issue due to author's lack of response for over a year

**Comment by strazto** [comment]
https://github.com/kshetline/ligatures-limited you might find this useful
