### ISSUE TITLE
Was the project abandoned?

### ISSUE THREAD

**Issue by kanlukasz** [CoenraadS/vscode-Disable-Ligatures#6]
as in title

**Comment by kshetline** [comment]
It appears so, but in the meantime, I've added this functionality (and smart ligature rendering in other contexts, besides the current caret position), in [Ligatures Limited](https://marketplace.visualstudio.com/items?itemName=kshetline.ligatures-limited), with the repo here: https://github.com/kshetline/ligatures-limited

**Comment by kanlukasz** [comment]
It is sad that the developer has not been able to give a simple answer for several months 🤷‍♂️
Thanks for @kshetline answer! I will try your addon
