### ISSUE TITLE
Ligatures are not being disabled in vscode 1.49 

### ISSUE THREAD

**Issue by BenLanglois** [CoenraadS/vscode-Disable-Ligatures#7]
## Description

Upgrading to vscode version 1.49 (August 2020) causes ligatures to not be disabled by this extension, in both cursor and line mode. I downgraded to vscode version 1.48 (July 2020) and the extension works as expected.

## System Info

- Disable Ligatures v0.0.8
- macOS 10.14.6

**Comment by BenLanglois** [comment]
I also submitted a similar issue in the ligatures limited extension: https://github.com/kshetline/ligatures-limited/issues/19

**Comment by kshetline** [comment]
If you replace `createTextEditorDecorationType({ color: '' })` with `createTextEditorDecorationType({ after: { contentText: '\u200A', width: '0' } })` that will likely fix the problem. I'd originally copied your `color: ''` trick for breaking up ligatures for use in my own extension, so hopefully my fix with work for you too.

**Comment by Killea** [comment]
> If you replace `createTextEditorDecorationType({ color: '' })` with `createTextEditorDecorationType({ after: { contentText: '\u200A', width: '0' } })` that will likely fix the problem. I'd originally copied your `color: ''` trick for breaking up ligatures for use in my own extension, so hopefully my fix with work for you too.

Thanks, kshetlien, works fine!

**Comment by CoenraadS** [comment]
I found time to update it, but I recommend using a more actively maintained extension such as: https://marketplace.visualstudio.com/items?itemName=kshetline.ligatures-limited
